export const CATALOG = {
  1: { name: "Magnetic Vacuum Phone Holder", sku: "CJYD227014202BY", price: 24.99, supplier: "CJ", cjVariantSku: "CJYD227014202BY", fulfillmentReady: false },
  2: { name: "Portable Rechargeable Blender", sku: "CJYD278208001AZ", price: 19.99, supplier: "CJ", cjVariantSku: "CJYD278208001AZ", fulfillmentReady: true },
  3: { name: "Portable Travel Jewellery Box", sku: "CJYD228090802BY", price: 19.99, supplier: "CJ", cjVariantSku: "CJYD228090802BY", fulfillmentReady: true },
  4: { name: "Rechargeable Fabric Lint Remover", sku: "CJYD192666301AZ", price: 14.99, supplier: "CJ", cjVariantSku: "CJYD192666301AZ", fulfillmentReady: true },
  5: { name: "Travel Cable Organiser Bag", sku: "CJJT107047201AZ", price: 14.99, supplier: "CJ", cjVariantSku: "CJJT107047201AZ", fulfillmentReady: true },
  6: { name: "Rechargeable Pet Nail Grinder", sku: "CJJJCWGY03580-Black set-USB", price: 17.99, supplier: "CJ", cjVariantSku: "CJJJCWGY03580-Black set-USB", fulfillmentReady: true },
  7: { name: "Foldable Clothes Storage Bag", sku: "CJYD237778201AZ", price: 16.99, supplier: "CJ", cjVariantSku: "CJYD237778201AZ", fulfillmentReady: true },
  8: { name: "Washable Pet Hair Remover", sku: "CJJT174982701AZ", price: 12.99, supplier: "CJ", cjVariantSku: "CJJT174982701AZ", fulfillmentReady: true },
  9: { name: "USB Desk Fan", sku: "PENDING-9", price: 14.99, supplier: null, fulfillmentReady: false },
  10: { name: "Wireless Charging Pad", sku: "PENDING-10", price: 16.99, supplier: null, fulfillmentReady: false },
  11: { name: "Bluetooth Shower Speaker", sku: "PENDING-11", price: 19.99, supplier: null, fulfillmentReady: false },
  12: { name: "Mini Keyboard Cleaner", sku: "PENDING-12", price: 9.99, supplier: null, fulfillmentReady: false },
  13: { name: "Phone Cable Protector Set", sku: "PENDING-13", price: 7.99, supplier: null, fulfillmentReady: false },
  14: { name: "LED Wardrobe Light", sku: "PENDING-14", price: 14.99, supplier: null, fulfillmentReady: false },
  15: { name: "Digital Alarm Clock", sku: "PENDING-15", price: 19.99, supplier: null, fulfillmentReady: false },
  16: { name: "Adjustable Laptop Stand", sku: "PENDING-16", price: 24.99, supplier: null, fulfillmentReady: false },
  17: { name: "Mini Desktop Humidifier", sku: "PENDING-17", price: 18.99, supplier: null, fulfillmentReady: false },
  18: { name: "Reusable Cable Ties", sku: "PENDING-18", price: 6.99, supplier: null, fulfillmentReady: false },
  19: { name: "Silicone Air Fryer Liner", sku: "PENDING-19", price: 11.99, supplier: null, fulfillmentReady: false },
  20: { name: "Kitchen Oil Spray Bottle", sku: "PENDING-20", price: 12.99, supplier: null, fulfillmentReady: false },
  21: { name: "Magnetic Spice Jars", sku: "PENDING-21", price: 17.99, supplier: null, fulfillmentReady: false },
  22: { name: "Silicone Sink Strainer", sku: "PENDING-22", price: 8.99, supplier: null, fulfillmentReady: false },
  23: { name: "Reusable Food Storage Bags", sku: "PENDING-23", price: 13.99, supplier: null, fulfillmentReady: false },
  24: { name: "Handheld Milk Frother", sku: "PENDING-24", price: 10.99, supplier: null, fulfillmentReady: false },
  25: { name: "Manual Vegetable Chopper", sku: "PENDING-25", price: 18.99, supplier: null, fulfillmentReady: false },
  26: { name: "Easy Release Ice Cube Tray", sku: "PENDING-26", price: 9.99, supplier: null, fulfillmentReady: false },
  27: { name: "Microwave Splatter Cover", sku: "PENDING-27", price: 12.99, supplier: null, fulfillmentReady: false },
  28: { name: "Clip-On Pot Strainer", sku: "PENDING-28", price: 10.99, supplier: null, fulfillmentReady: false },
  29: { name: "Sofa Armrest Organiser", sku: "PENDING-29", price: 16.99, supplier: null, fulfillmentReady: false },
  30: { name: "Under-Bed Storage Organiser", sku: "PENDING-30", price: 19.99, supplier: null, fulfillmentReady: false },
  31: { name: "Adjustable Drawer Divider Set", sku: "PENDING-31", price: 15.99, supplier: null, fulfillmentReady: false },
  32: { name: "Bathroom Shower Caddy", sku: "PENDING-32", price: 17.99, supplier: null, fulfillmentReady: false },
  33: { name: "Travel Shoe Storage Bags", sku: "PENDING-33", price: 12.99, supplier: null, fulfillmentReady: false },
  34: { name: "Bedside Pocket Organiser", sku: "PENDING-34", price: 13.99, supplier: null, fulfillmentReady: false },
  35: { name: "Microfibre Cleaning Slippers", sku: "PENDING-35", price: 9.99, supplier: null, fulfillmentReady: false },
  36: { name: "Portable Pet Water Bottle", sku: "PENDING-36", price: 15.99, supplier: null, fulfillmentReady: false },
  37: { name: "Slow Feeder Dog Bowl", sku: "PENDING-37", price: 14.99, supplier: null, fulfillmentReady: false },
  38: { name: "Self-Cleaning Cat Grooming Brush", sku: "PENDING-38", price: 13.99, supplier: null, fulfillmentReady: false },
  39: { name: "Adjustable Pet Seat Belt", sku: "PENDING-39", price: 9.99, supplier: null, fulfillmentReady: false },
  40: { name: "Dog Paw Cleaner Cup", sku: "PENDING-40", price: 12.99, supplier: null, fulfillmentReady: false },
  41: { name: "Pet Treat Training Pouch", sku: "PENDING-41", price: 14.99, supplier: null, fulfillmentReady: false },
  42: { name: "Travel Makeup Organiser", sku: "PENDING-42", price: 18.99, supplier: null, fulfillmentReady: false },
  43: { name: "Heatless Curling Set", sku: "PENDING-43", price: 11.99, supplier: null, fulfillmentReady: false },
  44: { name: "Makeup Brush Cleaning Pad", sku: "PENDING-44", price: 7.99, supplier: null, fulfillmentReady: false },
  45: { name: "Satin Sleep Mask", sku: "PENDING-45", price: 9.99, supplier: null, fulfillmentReady: false },
  46: { name: "Jewellery Cleaning Pen", sku: "PENDING-46", price: 8.99, supplier: null, fulfillmentReady: false },
  47: { name: "Silicone Scalp Massager", sku: "PENDING-47", price: 8.99, supplier: null, fulfillmentReady: false },
  48: { name: "Resistance Band Set", sku: "PENDING-48", price: 17.99, supplier: null, fulfillmentReady: false },
  49: { name: "Yoga Stretch Strap", sku: "PENDING-49", price: 9.99, supplier: null, fulfillmentReady: false },
  50: { name: "Adjustable Hand Grip Trainer", sku: "PENDING-50", price: 12.99, supplier: null, fulfillmentReady: false },
  51: { name: "Running Waist Belt", sku: "PENDING-51", price: 14.99, supplier: null, fulfillmentReady: false },
  52: { name: "Travel Packing Cube Set", sku: "PENDING-52", price: 19.99, supplier: null, fulfillmentReady: false },
  53: { name: "Luggage Cup Holder", sku: "PENDING-53", price: 12.99, supplier: null, fulfillmentReady: false },
  54: { name: "RFID Passport Wallet", sku: "PENDING-54", price: 14.99, supplier: null, fulfillmentReady: false },
  55: { name: "Car Seat Gap Organiser", sku: "PENDING-55", price: 17.99, supplier: null, fulfillmentReady: false },
  56: { name: "Car Interior Cleaning Gel", sku: "PENDING-56", price: 8.99, supplier: null, fulfillmentReady: false },
  57: { name: "Mini Car Rubbish Bin", sku: "PENDING-57", price: 13.99, supplier: null, fulfillmentReady: false },
  58: { name: "Hard Shell Sunglasses Case", sku: "PENDING-58", price: 10.99, supplier: null, fulfillmentReady: false }
};

export function isFulfillmentReady(product) {
  return Boolean(product?.fulfillmentReady);
}
