[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/checkout-quote"
  to = "/.netlify/functions/checkout-quote"
  status = 200

[[redirects]]
  from = "/api/create-order"
  to = "/.netlify/functions/create-order"
  status = 200

[[redirects]]
  from = "/api/capture-order"
  to = "/.netlify/functions/capture-order"
  status = 200


[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200
