const PRODUCTS = [
  {
    "id": 1,
    "name": "Magnetic Vacuum Phone Holder",
    "category": "Tech",
    "price": 24.99,
    "image": "https://down-my.img.susercontent.com/file/my-11134208-7rasc-m7rfzb9yn3w745",
    "emoji": "📱",
    "description": "Foldable magnetic phone holder for desks and car use.",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/magnetic-phone-holder-with-vacuum-suction-foldable-adjustable-car-mount-magnetic-bracket-suction-nonslip-for-busy-commuters-p-2501140539421621100.html",
    "supplierSku": "CJYD227014202BY",
    "fulfillmentReady": false,
    "supplierCostUSD": 9.85,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 2,
    "name": "Portable Rechargeable Blender",
    "category": "Kitchen",
    "price": 19.99,
    "image": "https://cf.cjdropshipping.com/quick/product/bef87977-9a0d-4099-826a-75bdcae7a2f9.jpg",
    "emoji": "🥤",
    "description": "Compact rechargeable blender for smoothies, juices and drinks at home, work or on the go.",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/portable-rechargeable-juice-blender-compact-handheld-electric-smoothie-maker-for-travel-office-home-p-2603100340021608800.html",
    "supplierSku": "CJYD278208001AZ",
    "fulfillmentReady": true,
    "supplierCostUSD": 5.47,
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 3,
    "name": "Portable Travel Jewellery Box",
    "category": "Accessories",
    "price": 19.99,
    "image": "https://cf.cjdropshipping.com/quick/product/5aaf2512-caa6-48f1-9a77-b653f497fca3.jpg",
    "emoji": "💍",
    "description": "Travel-friendly jewellery organiser with a soft-lined interior for rings, earrings and small accessories.",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/travel-easy-to-carry-dustproof-portable-jewelry-box-p-2501290753441625000.html",
    "supplierSku": "CJYD228090802BY",
    "fulfillmentReady": true,
    "supplierCostUSD": 6.8,
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 4,
    "name": "Rechargeable Fabric Lint Remover",
    "category": "Home",
    "price": 14.99,
    "image": "https://oss-cf.cjdropshipping.com/product/2024/06/24/05/828407c7-959e-48b7-823f-914a45256f52.jpg",
    "emoji": "🧥",
    "description": "Rechargeable fabric shaver with a digital battery display for clothing and soft furnishings.",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/lint-remover-for-clothing-portable-electric-fuzz-pellet-remover-led-display-rechargeable-for-clothes-fabric-shaver-fluff-remover-p-1737785083941105664.html",
    "supplierSku": "CJYD192666301AZ",
    "fulfillmentReady": true,
    "supplierCostUSDRange": [
      3.35,
      4.31
    ],
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 5,
    "name": "Travel Cable Organiser Bag",
    "category": "Tech",
    "price": 14.99,
    "image": "https://cc-west-usa.oss-accelerate.aliyuncs.com/1617858526212.jpg",
    "emoji": "🔌",
    "description": "Water-resistant organiser for cables, chargers, power banks and small electronics.",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/cable-organizer-bag-travel-electronic-accessories-carrying-case-for-digital-camera-usb-charger-power-bank-storage-bag-box-p-1380028552015122432.html",
    "supplierSku": "CJJT107047201AZ",
    "fulfillmentReady": true,
    "supplierCostUSD": 3.95,
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 6,
    "name": "Rechargeable Pet Nail Grinder",
    "category": "Pets",
    "price": 17.99,
    "image": "https://cf.cjdropshipping.com/1613441955926.jpg",
    "emoji": "🐾",
    "description": "USB rechargeable black pet nail grinder set designed for gentle dog and cat nail care.",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/rechargeable-usb-pet-automatic-dog-nail-grinder-animal-clipper-p-C0175213-1A1D-4688-BC1D-179F5D5B1702.html",
    "supplierSku": "CJJJCWGY03580-Black set-USB",
    "fulfillmentReady": true,
    "supplierCostUSDRange": [
      0.74,
      10.42
    ],
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 7,
    "name": "Foldable Clothes Storage Bag",
    "category": "Home",
    "price": 16.99,
    "image": "https://oss-cf.cjdropshipping.com/product/2026/09/01/07/2625f844-4a70-4142-b8fe-18b826aae414.jpg",
    "emoji": "🧺",
    "description": "Large-capacity foldable storage bag with handles and a double-zip closure for clothes and bedding.",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/foldable-clothes-storage-bag-large-capacity-organizer-with-handle-and-double-zipper-for-bedding-moving-travel-under-bed-storage-p-2505160457141629100.html",
    "supplierSku": "CJYD237778201AZ",
    "fulfillmentReady": true,
    "supplierCostUSDRange": [
      0.98,
      5.65
    ],
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 8,
    "name": "Washable Pet Hair Remover",
    "category": "Pets",
    "price": 12.99,
    "image": "https://cf.cjdropshipping.com/b477b6a9-6e19-4e44-b6f0-f7262aef17ee.jpg",
    "emoji": "🐶",
    "description": "Reusable washable adhesive roller for lifting pet hair, lint and dust from clothes, sofas and car seats.",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/portable-washable-hair-remover-with-adhesive-roller-p-1653949161269637120.html",
    "supplierSku": "CJJT174982701AZ",
    "fulfillmentReady": true,
    "supplierCostUSDRange": [
      2.63,
      4.75
    ],
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 9,
    "name": "USB Desk Fan",
    "category": "Tech",
    "price": 14.99,
    "image": "https://www.gaiatop.com/cdn/shop/files/Z6_02e3e3b7-e450-43e7-a515-2cd2531f2525.jpg?v=1750739033&width=1080",
    "emoji": "🌬️",
    "description": "Compact USB desk fan for workspaces, bedrooms and study areas.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/robot-fan-usb-rechargeable-desk-fan-mini-digital-display-table-fan-with-suction-cup-portable-cooling-office-car-travel-p-2605210317481625600.html",
    "supplierSku": "CJJT289858001AZ",
    "supplierCostUSD": 4.7,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 10,
    "name": "Wireless Charging Pad",
    "category": "Tech",
    "price": 16.99,
    "image": "https://www.meintrendyhandy.de/images/Universal-Fast-Wireless-Charger-Black-02082019-01-p.webp",
    "emoji": "🔋",
    "description": "Slim wireless charging pad for compatible phones and earbuds.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/desktop-phone-ultra-thin-round-wireless-charger-p-2412261234571625200.html",
    "supplierSku": "CJSJ225461401AZ",
    "supplierCostUSDRange": [
      3.19,
      3.86
    ],
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 11,
    "name": "Bluetooth Shower Speaker",
    "category": "Tech",
    "price": 19.99,
    "image": "https://img.pccomponentes.com/articles/43/431477/3504-spc-splash-2-altavoz-bluetooth-ducha-azul-mejor-precio.jpg",
    "emoji": "🔊",
    "description": "Compact splash-resistant speaker for bathrooms, travel and outdoor use.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/waterproof-bluetooth-speaker-p-5EA5109E-F6FB-45A3-8556-8B67D9EBA96C.html",
    "supplierSku": "CJXFJTYP00114-Grey",
    "supplierCostUSD": 7.39,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 12,
    "name": "Mini Keyboard Cleaner",
    "category": "Tech",
    "price": 9.99,
    "image": "https://images.bauerhosting.com/affiliates/sites/8/2023/09/2-2.png?auto=format&q=80&w=1440",
    "emoji": "⌨️",
    "description": "Handy cleaning tool for keyboards, earbuds and small electronics.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/portable-11-in-1-multifunctional-cleaning-kit-computer-keyboard-cleaner-phone-screen-clean-tools-earphone-clean-brush-with-storage-box-p-2503061121491606900.html",
    "supplierSku": "CJYD231771001AZ",
    "supplierCostUSD": 1.45,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 13,
    "name": "Phone Cable Protector Set",
    "category": "Tech",
    "price": 7.99,
    "image": "https://i5.walmartimages.cl/asr/5159cf35-acef-4385-999f-0ad47d2a8a24.61e7b143850ddcbe2aacee7e6f049d22.jpeg?odnBg=FFFFFF&odnHeight=612&odnWidth=612",
    "emoji": "🔌",
    "description": "Flexible cable protectors designed to reduce everyday wire wear.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/common-for-data-cable-protection-wire-wrapping-p-1577242830689546240.html",
    "supplierSku": "CJSJ157935901AZ",
    "supplierCostUSD": 0.36,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 14,
    "name": "LED Wardrobe Light",
    "category": "Home",
    "price": 14.99,
    "image": "https://www.tecnomat.it/pub/media/catalog/product/c/b/2/f/reglette_per_armadio_con_sensore_di_movimento_w_lumen_k_mm_25035187_picture_01.jpg",
    "emoji": "💡",
    "description": "Compact LED light for wardrobes, cupboards and dark storage areas.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/led-sensor-light-body-infrared-sensor-light-led-cabinet-light-p-F91CA00A-6403-435D-8E5A-5555B4D78FFA.html",
    "supplierSku": "CJJZSNSN00255-Recharge 10LED-1pcs",
    "supplierCostUSDFrom": 2.69,
    "supplierMatchStatus": "matched-awaiting-exact-variant-cost-and-uk-shipping",
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 15,
    "name": "Digital Alarm Clock",
    "category": "Home",
    "price": 19.99,
    "image": "https://cdn0.woolworths.media/content/wowproductimages/large/1115191827_8.jpg",
    "emoji": "⏰",
    "description": "Simple digital bedside clock with an easy-read display.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/cross-border-hit-digital-bedroom-student-led-electronic-simple-mini-car-plug-in-clock-small-alarm-clock-p-1954842383395475457.html",
    "supplierSku": "CJJT245323701AZ",
    "supplierCostUSD": 4.53,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 16,
    "name": "Adjustable Laptop Stand",
    "category": "Tech",
    "price": 24.99,
    "image": "https://www.nillkin.com/cdn/shop/products/ProDeskAdjustableLaptopStand-Sliver.jpg?v=1690029878&width=1000",
    "emoji": "💻",
    "description": "Portable adjustable stand for laptops and tablets.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/new-laptop-stand-multifunctional-folding-lift-portable-laptop-stand-monitor-increase-rack-aluminum-alloy-base-p-DCB495CC-80F8-4ED9-B5BD-26E39B751776.html",
    "supplierSku": "CJJSBGBG00898-Black-280x280x25.5mm",
    "supplierCostUSD": 11.82,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 17,
    "name": "Mini Desktop Humidifier",
    "category": "Home",
    "price": 18.99,
    "image": "https://media.adeo.com/mkp/6d2241b63da7bde0e56a77f2a0018501/media.jpg?fit=bounds&format=jpg&height=650&quality=80&width=650",
    "emoji": "💧",
    "description": "Compact desktop humidifier for bedrooms, desks and small spaces.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/usb-mini-humidifier-large-fog-volume-small-air-hydrating-humidifier-p-1495774597293936640.html",
    "supplierSku": "CJJT142131101AZ",
    "supplierCostUSD": 2.45,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 18,
    "name": "6-Pack Magnetic Cable Clips",
    "category": "Tech",
    "price": 12.99,
    "image": "https://cf.cjdropshipping.com/17174592/2406040438510321900.jpg",
    "emoji": "🧷",
    "description": "Six white magnetic cable clips for keeping charging leads and desk wires tidy and within easy reach.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "sourcingNote": "Pinned to CJ SKU CJYD197888501AZ (6 Pack White). Planned price raised so the product-level margin remains acceptable even using the top of CJ's public family price range.",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/magnetic-cable-clip-under-desk-cable-management-adjustable-cord-holder-wire-organizer-and-cable-management-wire-keeper-p-1763402968205897728.html",
    "supplierSku": "CJYD197888501AZ",
    "supplierCostUSDRange": [
      0.05,
      8.45
    ],
    "replacedFromName": "Reusable Cable Ties"
  },
  {
    "id": 19,
    "name": "Silicone Air Fryer Liner",
    "category": "Kitchen",
    "price": 11.99,
    "image": "https://img.joomcdn.net/6c89682b8c8e9b6bc4089013d73b8dcafa48a008_original.jpeg",
    "emoji": "🍟",
    "description": "Reusable silicone liner designed to make air fryer cleanup easier.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/air-fryer-silicone-pot-replacement-of-parchment-paper-liners-no-more-cleaning-basket-after-using-the-air-fryer-food-safe-air-fryers-oven-accessories-p-1435061247828692992.html",
    "supplierSku": "CJJT127784001AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      3.93,
      5.43
    ],
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 20,
    "name": "Kitchen Oil Spray Bottle",
    "category": "Kitchen",
    "price": 12.99,
    "image": "https://image.cdn.shpy.in/371084/SKU-8108_0-1755611834756.jpg?format=webp&width=600",
    "emoji": "🫙",
    "description": "Refillable fine-mist oil bottle for cooking and salads.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/2-in-1-oil-sprayer-bottle-bbq-cooking-oil-dispenser-olive-oil-pourers-sprayer-kitchen-baking-oil-mister-vinegar-bottle-p-1715574082122551296.html",
    "supplierSku": "CJYD187611401AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      3.01,
      5.66
    ],
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 21,
    "name": "Magnetic Kitchen Seasoning Rack",
    "category": "Kitchen",
    "price": 17.99,
    "image": "https://cf.cjdropshipping.com/quick/product/1dd0ac8b-78ce-4867-8987-5201522fa425.jpg",
    "emoji": "🧂",
    "description": "Space-saving magnetic kitchen rack for seasonings, condiments and small everyday cooking essentials.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "matched-awaiting-variant-and-uk-shipping",
    "sourcingNote": "Replace current draft listing with Magnetic Kitchen Seasoning Rack before launch. Supplier and product cost are matched; customer-facing title/image still need to be switched to the replacement.",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/wall-mounted-storage-rack-household-kitchen-seasoning-product-seasoning-p-2406160346461601500.html",
    "supplierSku": "CJYD206141801AZ",
    "supplierCostUSDRange": [
      1.76,
      7.89
    ],
    "replacedFromName": "Magnetic Spice Jars"
  },
  {
    "id": 22,
    "name": "Silicone Sink Strainer",
    "category": "Kitchen",
    "price": 8.99,
    "image": "https://i5.walmartimages.com/asr/6d2592c9-8a1e-45a9-9004-146a35a2eba0.fc4f126d074eb5f7cf53b79d044bf6af.jpeg?odnBg=FFFFFF&odnHeight=768&odnWidth=768",
    "emoji": "🚰",
    "description": "Flexible sink strainer for catching food scraps and debris.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/sink-drain-strainer-hair-catchers-rubber-shower-bathtub-floor-filter-water-stopper-silicone-bathroom-kitchen-deodorant-plug-p-1382324639715430400.html",
    "supplierSku": "CJYS108057501AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      0.52,
      2.72
    ],
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 23,
    "name": "Reusable Food Storage Bags",
    "category": "Kitchen",
    "price": 13.99,
    "image": "https://tm-prd-cdn.themarket.co.nz/resizer/view?b=productimages&h=1080&key=740783a859ab1e263eac67d7c6fb8ca6&w=1080",
    "emoji": "🥪",
    "description": "Reusable storage bags for snacks, lunches and food prep.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/silicone-fresh-keeping-bag-vacuum-sealed-bag-food--storage-bag-refrigerator-food-fruit-storage-bag-p-3F459E7B-ECA7-4DE5-86BB-B76413905F0C.html",
    "supplierSku": "CJJJJTCF00348-Blue-500ml",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      1.3,
      8.35
    ],
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 24,
    "name": "Handheld Milk Frother",
    "category": "Kitchen",
    "price": 10.99,
    "image": "https://www.bigw.com.au/medias/sys_master/images/images/h69/hca/120105267691550.jpg",
    "emoji": "☕",
    "description": "Compact handheld frother for coffee, hot chocolate and shakes.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/modern-minimalist-handheld-electric-milk-powder-stirrer-p-2408020406281627600.html",
    "supplierSku": "CJYD209951701AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 1.24,
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 25,
    "name": "Manual Vegetable Chopper",
    "category": "Kitchen",
    "price": 18.99,
    "image": "https://i5.walmartimages.com/asr/24f7bd1c-2686-4db8-b38b-e27ac6ef7327.9540be5c952c8a8601cfed3cbc5ab769.jpeg?odnBg=FFFFFF&odnHeight=580&odnWidth=580",
    "emoji": "🥕",
    "description": "Compact kitchen chopper for quick everyday food preparation.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/kitchen-hand-operated-multi-functional-vegetable-cutter-rust-resistant-practical-manual-vegetable-slicer-for-home-p-1630393947791044608.html",
    "supplierSku": "CJJT169443501AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 6.09,
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 26,
    "name": "Easy Release Ice Cube Tray",
    "category": "Kitchen",
    "price": 9.99,
    "image": "https://st.bigc-cs.com/cdn-cgi/image/format%3Dwebp%2Cquality%3D90/public/media/catalog/product/50/20/2000006206350/2000006206350_3-20240528152152-.jpg",
    "emoji": "🧊",
    "description": "Flexible ice tray designed for quick, easy cube release.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/pp-material-ice-mould-quick-demould-ice-cube-tray-creative-party-bar-kitchen-freezer-cooling-drink-ice-box-silicone-molds-kitchen-gadgets-p-1798951781255487488.html",
    "supplierSku": "CJYD205527401AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      0.5,
      1.65
    ],
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 27,
    "name": "6-Piece Reusable Silicone Stretch Lid Set",
    "category": "Kitchen",
    "price": 14.99,
    "image": "https://cc-west-usa.oss-accelerate.aliyuncs.com/453266a9-0f09-4397-8c13-f127319791f7.jpg",
    "emoji": "🍲",
    "description": "Six reusable stretchy silicone food covers in assorted sizes for bowls, containers, fruit and everyday fridge storage.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierSku": "CJCF1723695-1Set",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "sourcingNote": "Pinned to CJ SKU CJCF1723695-1Set. CJ's public page shows 1Set selected and a $6.42–$9.18 family range; planned price is safe even at the top of that public range.",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplierUrl": "https://cjdropshipping.com/product/6pcs-food-silicone-cover-fresh-keeping-dish-stretchy-lid-cap-reusable-wrap-organization-storage-tool-kitchen-accessories-6pcs-silicone-stretch-lids-p-1642738075405537280.html",
    "supplierCostUSDRange": [
      6.42,
      9.18
    ],
    "replacedFromName": "Microwave Splatter Cover"
  },
  {
    "id": 28,
    "name": "Silicone Pot Utensil Clip",
    "category": "Kitchen",
    "price": 10.99,
    "image": "https://cf.cjdropshipping.com/quick/product/b1a52512-cdcc-49fa-ae4b-572db5fb035b.jpg",
    "emoji": "🍝",
    "description": "Heat-resistant silicone clip designed to hold spoons or utensils at the side of a cooking pot.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "matched-awaiting-variant-and-uk-shipping",
    "sourcingNote": "Replace current draft listing with Silicone Pot Utensil Clip before launch. Supplier and product cost are matched; customer-facing title/image still need to be switched to the replacement.",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/multifunctional-spatula-holder-silicone-anti-overflow-spoon-holder-cooking-pot-anti-scalding-clip-kitchen-gadgets-p-1767745182079913984.html",
    "supplierSku": "CJYD198735501AZ",
    "supplierCostUSDRange": [
      0.13,
      0.39
    ],
    "replacedFromName": "Clip-On Pot Strainer"
  },
  {
    "id": 29,
    "name": "Leather Remote Control Organiser",
    "category": "Home",
    "price": 16.99,
    "image": "https://cf.cjdropshipping.com/quick/product/86d06f2e-4084-424a-a0fd-2733d60f7bed.jpg",
    "emoji": "🛋️",
    "description": "Compact leather-look organiser for remote controls, phones, stationery and small household items.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "matched-awaiting-variant-and-uk-shipping",
    "sourcingNote": "Replace current draft listing with Leather Remote Control Organiser before launch. Supplier and product cost are matched; customer-facing title/image still need to be switched to the replacement.",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/household-supplies-remote-control-storage-box-of-leather-p-2407080721531609400.html",
    "supplierSku": "CJJT207840701AZ",
    "supplierCostUSDRange": [
      3.44,
      5.95
    ],
    "replacedFromName": "Sofa Armrest Organiser"
  },
  {
    "id": 30,
    "name": "Under-Bed Storage Organiser",
    "category": "Home",
    "price": 19.99,
    "image": "https://img.vevorstatic.com/us/CDCWFBWFBWL309XD1001V0/original_img-v1/under-bed-storage-m100-10.jpg?format=webp&timestamp=1751100891000",
    "emoji": "📦",
    "description": "Low-profile storage organiser for bedding, clothes and seasonal items.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/foldable-clothes-storage-bag-large-capacity-organizer-with-handle-and-double-zipper-for-bedding-moving-travel-under-bed-storage-p-2505160457141629100.html",
    "supplierSku": "CJYD237778201AZ",
    "supplierMatchStatus": "candidate-duplicate-review",
    "supplierCostUSDRange": [
      0.98,
      5.65
    ],
    "sourcingNote": "Good product match, but this is the same CJ family already used by product 7. Decide whether to keep both listings.",
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 31,
    "name": "Desktop Storage Box",
    "category": "Home",
    "price": 15.99,
    "image": "https://oss-cf.cjdropshipping.com/product/2024/07/24/02/2d681fb9-91e7-4f45-ac40-1ff900749d44_trans.jpeg",
    "emoji": "🗄️",
    "description": "Stackable drawer-style storage box for desks, bathrooms, cosmetics and small household essentials.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "matched-awaiting-variant-and-uk-shipping",
    "sourcingNote": "Replace current draft listing with Desktop Storage Box before launch. Supplier and product cost are matched; customer-facing title/image still need to be switched to the replacement.",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/desktop-storage-box-office-accessories-makeup-plastic-storage-container-bathroom-storage-stackable-organizer-drawer-p-1386883997170274304.html",
    "supplierSku": "CJJT110132001AZ",
    "supplierCostUSDRange": [
      1.92,
      5.58
    ],
    "replacedFromName": "Adjustable Drawer Divider Set"
  },
  {
    "id": 32,
    "name": "Bathroom Shower Caddy",
    "category": "Home",
    "price": 17.99,
    "image": "https://www.thursdayliving.com.au/cdn/shop/files/100725-3_07f2c409-a683-4abc-9c1b-a891e6e8be72.jpg?v=1754364230&width=1000",
    "emoji": "🚿",
    "description": "Compact shower organiser for toiletries and bathroom essentials.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/1pc-wall-mounted-bathroom-shelf-shower-caddy-rack-no-punching-triangle-storage-rack-for-bathroom-kitchen-bathroom-accessories-p-1880165726661005314.html",
    "supplierSku": "CJYS227337901AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 5.8,
    "sourcingNote": "CJ page also shows an $8.80 free-shipping price; live UK checkout must decide the real landed cost.",
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 33,
    "name": "Short-Distance Travel Bag",
    "category": "Travel",
    "price": 12.99,
    "image": "https://cf.cjdropshipping.com/quick/product/d78739ac-f265-456a-83bf-95460d91211e.jpg",
    "emoji": "👟",
    "description": "Lightweight Oxford-cloth travel bag with a roomy 20–35L capacity for weekends, fitness and short trips.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "sourcingNote": "Replace current draft listing with Short-Distance Travel Bag before launch. Supplier and product cost are matched; customer-facing title/image still need to be switched to the replacement.",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/fashion-short-distance-travel-bag-fitness-and-lightweight-p-2406080934471622000.html",
    "supplierSku": "CJYD205630901AZ",
    "supplierCostUSD": 5.97,
    "replacedFromName": "Travel Shoe Storage Bags"
  },
  {
    "id": 34,
    "name": "Bedside Pocket Organiser",
    "category": "Home",
    "price": 13.99,
    "image": "https://dreamsleepaustralia.com.au/cdn/shop/files/2_9bd47ec8-9693-4714-a674-6bbfbb436d37_1000x.png?v=1746125237",
    "emoji": "🛏️",
    "description": "Hanging bedside organiser for books, remotes, phones and accessories.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/non-woven-storage-hanging-bag-multi-layer-hanging-type-p-1377611667902435328.html",
    "supplierSku": "CJGJ106277501AZ",
    "supplierMatchStatus": "candidate-title-use-review",
    "supplierCostUSD": 2.79,
    "sourcingNote": "Hanging storage bag is close to a bedside pocket organiser, but the supplier describes it as a wall/door hanging organiser.",
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 35,
    "name": "Microfibre Cleaning Cloth Set",
    "category": "Home",
    "price": 9.99,
    "image": "https://cc-west-usa.oss-accelerate.aliyuncs.com/15097248/3575094129_405944515.400x400.jpg",
    "emoji": "🥿",
    "description": "Reusable microfibre cloth set for screens, glasses and light everyday cleaning.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "matched-awaiting-variant-and-uk-shipping",
    "sourcingNote": "Replace current draft listing with Microfibre Cleaning Cloth Set before launch. Supplier and product cost are matched; customer-facing title/image still need to be switched to the replacement.",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/screen-microfiber-screen-cleaning-cloth-p-18234200-0771-414B-B9F7-2048AC7E2E25.html",
    "supplierSku": "CJJJYSFZ00162-White-6x8cm-Q20pcs",
    "supplierCostUSDRange": [
      1.3,
      1.84
    ],
    "replacedFromName": "Microfibre Cleaning Slippers"
  },
  {
    "id": 36,
    "name": "Portable Pet Water Bottle",
    "category": "Pets",
    "price": 15.99,
    "image": "https://f.fcdn.app/imgs/a0a352/www.atrixuy.com/atriuy/de3f/original/catalogo/TBANI300_BLANCO_1/600x600/bebedero-portatil-mascotas-boton-dispensador-agua-viaje-color-variante-blanco.jpg",
    "emoji": "🐕",
    "description": "Portable water bottle for dogs during walks and travel.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/2-in-1-portable-dog-water-bottle-for-small-big-dogs-cat-outdoor-leak-proof-puppy-drinking-bowl-with-food-container-pets-feeder-pet-products-p-2504100230321610200.html",
    "supplierSku": "CJYD235019202BY",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      2.21,
      2.77
    ],
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 37,
    "name": "Slow Feeder Dog Bowl",
    "category": "Pets",
    "price": 14.99,
    "image": "https://tassukauppa.fi/WebRoot/elisa03/Shops/tassukauppa/63F6/711B/93E2/101E/A583/0A28/1012/16D3/Duvo_Slow_Feeder_ahmimisenestokuppi_koiralle_petrooli_S_LG14292.jpg",
    "emoji": "🥣",
    "description": "Patterned feeding bowl designed to encourage slower eating.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/pet-dog-cat-slow-feeder-bowls-anti-choking-slow-feeder-dish-bowl-home-dog-eating-plate-anti-gulping-bowl-supplies-p-1653041912300969984.html",
    "supplierSku": "CJGY174846501AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      1.29,
      2.11
    ],
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 38,
    "name": "Self-Cleaning Cat Grooming Brush",
    "category": "Pets",
    "price": 13.99,
    "image": "https://cdn.shopify.com/s/files/1/0573/2463/4249/files/self_cleaning_sliker_brush_detail.png?v=1693189057",
    "emoji": "🐈",
    "description": "Grooming brush with an easy-release design for loose pet hair.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/pet-needle-comb-hair-remover-brush-dog-and-cat-pet-comb-self-cleaning-massage-brushes-grooming-supplies-p-2407110256221627600.html",
    "supplierSku": "CJYD208071305EV",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 1.19,
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 39,
    "name": "Adjustable Pet Seat Belt",
    "category": "Pets",
    "price": 9.99,
    "image": "https://assets.petco.com/petco/image/upload/c_pad%2Cdpr_1.0%2Cf_auto%2Cq_auto%2Ch_636%2Cw_636/c_pad%2Ch_636%2Cw_636/3350102-center-1",
    "emoji": "🚗",
    "description": "Adjustable restraint strap for safer car journeys with pets.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/adjustable-pet-cat-dog-car-seat-belt-pet-seat-vehicle-dog-harness-lead-clip-safety-lever-traction-dog-collars-dogs-accessoires-pets-products-p-1383313727658528768.html",
    "supplierSku": "CJQC108431101AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      0.52,
      0.54
    ],
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 40,
    "name": "Pet Grooming Glove",
    "category": "Pets",
    "price": 12.99,
    "image": "https://oss-cf.cjdropshipping.com/product/2024/11/05/09/d84c55d3-fe54-458d-8f8f-f25e5d28881d_trans.jpeg",
    "emoji": "🐾",
    "description": "Grooming and massage glove for lifting loose pet hair during brushing or bathing.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "sourcingNote": "Replace current draft listing with Pet Grooming Glove before launch. Supplier and product cost are matched; customer-facing title/image still need to be switched to the replacement.",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/pet-comb-hair-bath-massage-gloves-p-2411040327401621100.html",
    "supplierSku": "CJYD218075601AZ",
    "supplierCostUSD": 1.47,
    "replacedFromName": "Dog Paw Cleaner Cup"
  },
  {
    "id": 41,
    "name": "Pet Treat Training Pouch",
    "category": "Pets",
    "price": 14.99,
    "image": "https://www.tiendanimal.es/dw/image/v2/BDLQ_PRD/on/demandware.static/-/Sites-kiwoko-master-catalog/default/dwa326554b/images/large/f17ddac57b0e4d0d8e2f5a954788ee76.jpg?q=85&sh=780&sm=fit&sw=780",
    "emoji": "🦴",
    "description": "Hands-free pouch for treats, waste bags and small training accessories.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/dog-training-leash-waist-bag-hands-free-outdoor-pet-running-walking-leash-portable-dog-food-water-cup-storage-bags-p-1392067844971302912.html",
    "supplierSku": "CJGY112387101AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "sourcingNote": "Pinned to CJ SKU CJGY112387101AZ, Grey. Current public CJ page shows a $3.32–$6.42 product range; even the high end leaves a healthy product-level margin at the current planned price.",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplierCostUSDRange": [
      3.32,
      6.42
    ]
  },
  {
    "id": 42,
    "name": "Travel Makeup Organiser",
    "category": "Accessories",
    "price": 18.99,
    "image": "https://igadgitz.com/cdn/shop/files/b7bb33e7-b339-475d-9bfd-1a75390ff00f_1800x1800.jpg?v=1738923558",
    "emoji": "💄",
    "description": "Multi-compartment makeup bag for holidays and everyday storage.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/travel-cosmetic-bag-large-capacity-multifunction-travel-cosmetic-bag-women-toiletries-organizer-female-storage-make-up-case-tool-p-1546430072087916544.html",
    "supplierSku": "CJNS152304201AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      1.46,
      1.58
    ],
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 43,
    "name": "Spiral Hair Curler & Comb Set",
    "category": "Beauty",
    "price": 11.99,
    "image": "https://cc-west-usa.oss-accelerate.aliyuncs.com/1615378680806.jpg",
    "emoji": "🎀",
    "description": "Hair styling set with spiral curling and comb tools for creating curls and waves.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "sourcingNote": "Replace current draft listing with Spiral Hair Curler & Comb Set before launch. Supplier and product cost are matched; customer-facing title/image still need to be switched to the replacement.",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/spiral-curler-comb-set-does-not-hurt-hair-titanium-alloy-splint-p-1369623902988406784.html",
    "supplierSku": "CJJT103762901AZ",
    "supplierCostUSD": 6.07,
    "replacedFromName": "Heatless Curling Set"
  },
  {
    "id": 44,
    "name": "Electric Makeup Brush Cleaner",
    "category": "Beauty",
    "price": 7.99,
    "image": "https://cf.cjdropshipping.com/17046720/2401080815100329800.jpg",
    "emoji": "🖌️",
    "description": "Compact USB-powered makeup brush cleaner designed for quick everyday cosmetic-brush cleaning.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "sourcingNote": "Replace current draft listing with Electric Makeup Brush Cleaner before launch. Supplier and product cost are matched; customer-facing title/image still need to be switched to the replacement.",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/electric-makeup-brush-cleaner-machine-portable-automatic-usb-cosmetic-brush-cleaner-tools-for-all-size-beauty-makeup-brushes-set-p-1707021717920550912.html",
    "supplierSku": "CJMJ185778101AZ",
    "supplierCostUSD": 1.93,
    "replacedFromName": "Makeup Brush Cleaning Pad"
  },
  {
    "id": 45,
    "name": "Silky Sleep Mask",
    "category": "Beauty",
    "price": 9.99,
    "image": "https://satinluxuryline.com/cdn/shop/files/16ASleepmask_recht_van_voren_roze_528d7372-6c08-483f-8d58-5f9b5076919b.jpg?v=1716319412&width=535",
    "emoji": "😴",
    "description": "Soft silky-feel sleep mask for travel, naps and bedtime routines.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/eye-patch-imitated-silk-eye-patch-shading-sleeping-eye-mask-travel-relax-covers-eye-shade-health-sleeping-shield-eye-care-tools-p-1692297554018447360.html",
    "supplierSku": "CJYD182485601AZ",
    "supplierMatchStatus": "candidate-material-title-review",
    "supplierCostUSD": 0.68,
    "sourcingNote": "CJ describes this as imitation silk/rayon. Rename the store item to Silky Sleep Mask unless a true satin variant is sourced.",
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 46,
    "name": "Velvet Jewellery Storage Pouch",
    "category": "Accessories",
    "price": 8.99,
    "image": "https://oss-cf.cjdropshipping.com/product/2025/08/03/03/79ef6bdf-a172-46ad-ac4a-4ad67f43e3fe_fine.jpeg",
    "emoji": "✨",
    "description": "Compact velvet snap-button jewellery pouch for rings, earrings and other small accessories.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "sourcingNote": "Switched to CJ's velvet jewellery pouch so the listing has a confirmed CJ-hosted product image and a narrow public price range.",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/oval-velvet-cloth-jewelry-storage-button-bag-jewelry-storage-bag-p-2508030355531612100.html",
    "supplierSku": "CJYD244638001AZ",
    "replacedFromName": "Jewellery Cleaning Pen",
    "supplierCostUSDRange": [
      0.4,
      0.5
    ]
  },
  {
    "id": 47,
    "name": "Silicone Scalp Massager",
    "category": "Beauty",
    "price": 8.99,
    "image": "https://5thave-img-cdn.beyondstyle.us/pf/bdacec14-10df-3aa2-955e-4bbebf6416b7.jpg?x-oss-process=style%2Fs1",
    "emoji": "💆",
    "description": "Soft silicone scalp brush for shampooing and massage.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/silicone-shampoo-head-brush-p-EC1FAEF4-5F97-462F-A67C-CDECF93BC026.html",
    "supplierSku": "CJJJJTJT51194-Pink",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplierCostUSD": 1.86,
    "sourcingNote": "Pinned to CJ SKU CJJJJTJT51194-Pink. CJ's public page shows Pink selected at $1.86."
  },
  {
    "id": 48,
    "name": "Resistance Band Set",
    "category": "Fitness",
    "price": 17.99,
    "image": "https://images.fyndiq.se/images/f_auto/t_600x600/prod/fdf2e18e548941b2/30bd544ac87b/5-pack-traningsband-gummiband-motstandsband-traningsband-multicolor-multifarg-0bc8718cbb254c57",
    "emoji": "🏋️",
    "description": "Portable resistance bands for home workouts and stretching.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/resistance-loop-exercise-bands-resistance-bands-exercise-bands-for-home-fitness-stretching-strength-training-physical-therapyelastic-workout-bands-for-women-men-kids-set-of-5-p-1809772680481492992.html",
    "supplierSku": "CJJM207746801AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 10.98,
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 49,
    "name": "Yoga Stretch Strap",
    "category": "Fitness",
    "price": 9.99,
    "image": "https://arrowmax.in/cdn/shop/files/4_9da76538-9cfe-4d8e-ad36-bd57cc14dd5f.jpg?v=1758272516",
    "emoji": "🧘",
    "description": "Simple stretching strap for yoga, mobility and flexibility work.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/rehabilitation-lajin-band-yoga-stretch-band-auxiliary-ligament-p-1441219130710691840.html",
    "supplierSku": "CJJT129735301AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 1.48,
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 50,
    "name": "Silicone Hand Grip Strengthener",
    "category": "Fitness",
    "price": 12.99,
    "image": "https://cf.cjdropshipping.com/17000928/1725002643480383488.jpg",
    "emoji": "💪",
    "description": "Compact silicone hand and finger strengthener for grip, forearm and everyday fitness exercises.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/hand-grip-strengthener-hand-finger-exerciser-forearm-rings-hand-exerciser-silicone-squeezer-grippers-for-finger-p-1724813769018183680.html",
    "supplierSku": "CJYD189795601AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "sourcingNote": "Replaced the wide-cost hand-grip family with CJ SKU CJYD189795601AZ (Pink), currently shown at a fixed $1.76 product price.",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplierCostUSD": 1.76
  },
  {
    "id": 51,
    "name": "Running Waist Belt",
    "category": "Fitness",
    "price": 14.99,
    "image": "https://fitletic.com/cdn/shop/products/0003_Blitz-Sports-and-Travel-Belt-Reflective-Black_600x.webp?v=1690219277",
    "emoji": "🏃",
    "description": "Slim waist belt for carrying phones, keys and cards while running.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/ultra-thin-running-waterproof-portable-close-fitting-reflective-sports-phone-waist-bag-p-2407010655361627900.html",
    "supplierSku": "CJYD207289401AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 2.11,
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 52,
    "name": "Travel Packing Cube Set",
    "category": "Travel",
    "price": 19.99,
    "image": "https://upandgr8.com/cdn/shop/files/9_b2d47f24-0e7c-4fd3-80d8-19040ccbba85.jpg?v=1715168268",
    "emoji": "🧳",
    "description": "Lightweight packing organisers for keeping luggage tidy.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/8-piece-set-luggage-divider-bag-travel-storage-clothes-underwear-shoes-organizer-packing-cube-bag-p-1386852733046362112.html",
    "supplierSku": "CJNS110086901AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      2.27,
      4.62
    ],
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 53,
    "name": "Travel Bottle Holder Strap",
    "category": "Travel",
    "price": 12.99,
    "image": "https://cc-west-usa.oss-accelerate.aliyuncs.com/cfe98f25-8367-48fb-a635-34b0d1c8b68b.jpg",
    "emoji": "🥤",
    "description": "Portable strap-style bottle holder for carrying a drink bottle during travel, walking and outdoor activities.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "sourcingNote": "Replace current draft listing with Travel Bottle Holder Strap before launch. Supplier and product cost are matched; customer-facing title/image still need to be switched to the replacement.",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/outdoor-travel-sports-portable-insulation-cup-strap-cover-p-1503992382675759104.html",
    "supplierSku": "CJNS143908201AZ",
    "supplierCostUSD": 0.71,
    "replacedFromName": "Luggage Cup Holder"
  },
  {
    "id": 54,
    "name": "RFID Passport Wallet",
    "category": "Travel",
    "price": 14.99,
    "image": "https://sc3.locondo.jp/contents/commodity_image/RE/RE4112DW06149_1_l.jpg",
    "emoji": "🛂",
    "description": "Compact travel wallet for passports, cards and documents.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/rfid-antimagnetic-passport-holder-leather-id-case-p-1BA30466-381C-44A5-8A86-8A2DFDF29A4C.html",
    "supplierSku": "CJBHNSNS10068-Black",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 3.35,
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 55,
    "name": "Car Seat Gap Organiser",
    "category": "Car",
    "price": 17.99,
    "image": "https://trunkistore.com/cdn/shop/files/20260105_2039_CarSeatGapFiller_remix_01ke6vsd59e74aymz7xhcd5bhj.png?v=1767609816&width=1024",
    "emoji": "🚙",
    "description": "Slim organiser for phones, keys and small items beside the car seat.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/car-seat-gap-filler-organizer-car-seat-console-organizer-for-keys-phones-and-sunglasses-p-1803978693954916352.html",
    "supplierSku": "CJQC206507501AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      4.34,
      8.46
    ],
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 56,
    "name": "Car Detail Cleaning Brush",
    "category": "Car",
    "price": 8.99,
    "image": "https://oss-cf.cjdropshipping.com/product/2024/06/02/01/c680b307-6d4f-4fcf-94d5-2d292a7868d6.jpg",
    "emoji": "🧽",
    "description": "Soft detailing brush for cleaning car vents, trim, seat gaps and other hard-to-reach interior areas.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "matched-awaiting-variant-and-uk-shipping",
    "sourcingNote": "Replace current draft listing with Car Detail Cleaning Brush before launch. Supplier and product cost are matched; customer-facing title/image still need to be switched to the replacement.",
    "pricingAuditStatus": "pricing-healthy-before-fees",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/car-detail-brush-soft-brush-interior-cleaning-p-1796519066690134016.html",
    "supplierSku": "CJYD205093001AZ",
    "supplierCostUSDRange": [
      0.7,
      1.5
    ],
    "replacedFromName": "Car Interior Cleaning Gel"
  },
  {
    "id": 57,
    "name": "Mini Car Rubbish Bin",
    "category": "Car",
    "price": 13.99,
    "image": "https://zybux.co.uk/cdn/shop/files/7_7398c628-7f62-403b-952b-9cc323d7b562_1445x.png?v=1684848608",
    "emoji": "🗑️",
    "description": "Compact car bin for wrappers, tissues and everyday rubbish.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/car-door-container-trash-can-p-2505210708001621800.html",
    "supplierSku": "CJYD238181101AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 2.28,
    "pricingAuditStatus": "pricing-healthy-before-fees"
  },
  {
    "id": 58,
    "name": "Protective Sunglasses Case",
    "category": "Accessories",
    "price": 10.99,
    "image": "https://knockaround.com/cdn/shop/products/KA_Hard_Shell_Black_Front.jpg?v=1761056420&width=1024",
    "emoji": "🕶️",
    "description": "Protective sunglasses case for keeping glasses safer in bags, cars and everyday storage.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/litchi-sunglasses-case-p-D2520D4F-0058-4148-AF2B-DF7E157539F3.html",
    "supplierSku": "CJNSFSYJ00303-Black a",
    "supplierMatchStatus": "candidate-material-title-review",
    "supplierCostUSDRange": [
      0.54,
      6.2
    ],
    "sourcingNote": "This is a protective leather sunglasses case, not explicitly a hard-shell case. Rename or source a confirmed hard-shell model.",
    "pricingAuditStatus": "pricing-healthy-before-fees"
  }
];

// Product pricing is audited against the highest known public CJ product price. Live UK shipping and final API validation still happen before launch.
