const PRODUCTS = [
  {
    "id": 1,
    "name": "Magnetic Vacuum Phone Holder",
    "category": "Tech",
    "price": 24.99,
    "image": "https://down-my.img.susercontent.com/file/my-11134208-7rasc-m7rfzb9yn3w745",
    "emoji": "📱",
    "description": "Foldable magnetic phone holder for desks and car use.",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/magnetic-phone-holder-with-vacuum-suction-foldable-adjustable-car-mount-magnetic-bracket-suction-nonslip-for-busy-commuters-p-2501140539421621100.html",
    "supplierSku": "CJYD227014202BY",
    "fulfillmentReady": false,
    "supplierCostUSD": 9.85,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check"
  },
  {
    "id": 2,
    "name": "Portable Rechargeable Blender",
    "category": "Kitchen",
    "price": 19.99,
    "image": "https://cf.cjdropshipping.com/quick/product/bef87977-9a0d-4099-826a-75bdcae7a2f9.jpg",
    "emoji": "🥤",
    "description": "Compact rechargeable blender for smoothies, juices and drinks at home, work or on the go.",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/portable-rechargeable-juice-blender-compact-handheld-electric-smoothie-maker-for-travel-office-home-p-2603100340021608800.html",
    "supplierSku": "CJYD278208001AZ",
    "fulfillmentReady": true
  },
  {
    "id": 3,
    "name": "Portable Travel Jewellery Box",
    "category": "Accessories",
    "price": 19.99,
    "image": "https://cf.cjdropshipping.com/quick/product/5aaf2512-caa6-48f1-9a77-b653f497fca3.jpg",
    "emoji": "💍",
    "description": "Travel-friendly jewellery organiser with a soft-lined interior for rings, earrings and small accessories.",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/travel-easy-to-carry-dustproof-portable-jewelry-box-p-2501290753441625000.html",
    "supplierSku": "CJYD228090802BY",
    "fulfillmentReady": true
  },
  {
    "id": 4,
    "name": "Rechargeable Fabric Lint Remover",
    "category": "Home",
    "price": 14.99,
    "image": "https://oss-cf.cjdropshipping.com/product/2024/06/24/05/828407c7-959e-48b7-823f-914a45256f52.jpg",
    "emoji": "🧥",
    "description": "Rechargeable fabric shaver with a digital battery display for clothing and soft furnishings.",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/lint-remover-for-clothing-portable-electric-fuzz-pellet-remover-led-display-rechargeable-for-clothes-fabric-shaver-fluff-remover-p-1737785083941105664.html",
    "supplierSku": "CJYD192666301AZ",
    "fulfillmentReady": true
  },
  {
    "id": 5,
    "name": "Travel Cable Organiser Bag",
    "category": "Tech",
    "price": 14.99,
    "image": "https://cc-west-usa.oss-accelerate.aliyuncs.com/1617858526212.jpg",
    "emoji": "🔌",
    "description": "Water-resistant organiser for cables, chargers, power banks and small electronics.",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/cable-organizer-bag-travel-electronic-accessories-carrying-case-for-digital-camera-usb-charger-power-bank-storage-bag-box-p-1380028552015122432.html",
    "supplierSku": "CJJT107047201AZ",
    "fulfillmentReady": true
  },
  {
    "id": 6,
    "name": "Rechargeable Pet Nail Grinder",
    "category": "Pets",
    "price": 17.99,
    "image": "https://cf.cjdropshipping.com/1613441955926.jpg",
    "emoji": "🐾",
    "description": "USB rechargeable black pet nail grinder set designed for gentle dog and cat nail care.",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/rechargeable-usb-pet-automatic-dog-nail-grinder-animal-clipper-p-C0175213-1A1D-4688-BC1D-179F5D5B1702.html",
    "supplierSku": "CJJJCWGY03580-Black set-USB",
    "fulfillmentReady": true
  },
  {
    "id": 7,
    "name": "Foldable Clothes Storage Bag",
    "category": "Home",
    "price": 16.99,
    "image": "https://oss-cf.cjdropshipping.com/product/2026/09/01/07/2625f844-4a70-4142-b8fe-18b826aae414.jpg",
    "emoji": "🧺",
    "description": "Large-capacity foldable storage bag with handles and a double-zip closure for clothes and bedding.",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/foldable-clothes-storage-bag-large-capacity-organizer-with-handle-and-double-zipper-for-bedding-moving-travel-under-bed-storage-p-2505160457141629100.html",
    "supplierSku": "CJYD237778201AZ",
    "fulfillmentReady": true
  },
  {
    "id": 8,
    "name": "Washable Pet Hair Remover",
    "category": "Pets",
    "price": 12.99,
    "image": "https://cf.cjdropshipping.com/b477b6a9-6e19-4e44-b6f0-f7262aef17ee.jpg",
    "emoji": "🐶",
    "description": "Reusable washable adhesive roller for lifting pet hair, lint and dust from clothes, sofas and car seats.",
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/portable-washable-hair-remover-with-adhesive-roller-p-1653949161269637120.html",
    "supplierSku": "CJJT174982701AZ",
    "fulfillmentReady": true
  },
  {
    "id": 9,
    "name": "USB Desk Fan",
    "category": "Tech",
    "price": 14.99,
    "image": "https://www.gaiatop.com/cdn/shop/files/Z6_02e3e3b7-e450-43e7-a515-2cd2531f2525.jpg?v=1750739033&width=1080",
    "emoji": "🌬️",
    "description": "Compact USB desk fan for workspaces, bedrooms and study areas.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/robot-fan-usb-rechargeable-desk-fan-mini-digital-display-table-fan-with-suction-cup-portable-cooling-office-car-travel-p-2605210317481625600.html",
    "supplierSku": "CJJT289858001AZ",
    "supplierCostUSD": 4.7,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check"
  },
  {
    "id": 10,
    "name": "Wireless Charging Pad",
    "category": "Tech",
    "price": 16.99,
    "image": "https://www.meintrendyhandy.de/images/Universal-Fast-Wireless-Charger-Black-02082019-01-p.webp",
    "emoji": "🔋",
    "description": "Slim wireless charging pad for compatible phones and earbuds.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/desktop-phone-ultra-thin-round-wireless-charger-p-2412261234571625200.html",
    "supplierSku": "CJSJ225461401AZ",
    "supplierCostUSDRange": [
      3.19,
      3.86
    ],
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check"
  },
  {
    "id": 11,
    "name": "Bluetooth Shower Speaker",
    "category": "Tech",
    "price": 19.99,
    "image": "https://img.pccomponentes.com/articles/43/431477/3504-spc-splash-2-altavoz-bluetooth-ducha-azul-mejor-precio.jpg",
    "emoji": "🔊",
    "description": "Compact splash-resistant speaker for bathrooms, travel and outdoor use.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/waterproof-bluetooth-speaker-p-5EA5109E-F6FB-45A3-8556-8B67D9EBA96C.html",
    "supplierSku": "CJXFJTYP00114-Grey",
    "supplierCostUSD": 7.39,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check"
  },
  {
    "id": 12,
    "name": "Mini Keyboard Cleaner",
    "category": "Tech",
    "price": 9.99,
    "image": "https://images.bauerhosting.com/affiliates/sites/8/2023/09/2-2.png?auto=format&q=80&w=1440",
    "emoji": "⌨️",
    "description": "Handy cleaning tool for keyboards, earbuds and small electronics.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/portable-11-in-1-multifunctional-cleaning-kit-computer-keyboard-cleaner-phone-screen-clean-tools-earphone-clean-brush-with-storage-box-p-2503061121491606900.html",
    "supplierSku": "CJYD231771001AZ",
    "supplierCostUSD": 1.45,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check"
  },
  {
    "id": 13,
    "name": "Phone Cable Protector Set",
    "category": "Tech",
    "price": 7.99,
    "image": "https://i5.walmartimages.cl/asr/5159cf35-acef-4385-999f-0ad47d2a8a24.61e7b143850ddcbe2aacee7e6f049d22.jpeg?odnBg=FFFFFF&odnHeight=612&odnWidth=612",
    "emoji": "🔌",
    "description": "Flexible cable protectors designed to reduce everyday wire wear.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/common-for-data-cable-protection-wire-wrapping-p-1577242830689546240.html",
    "supplierSku": "CJSJ157935901AZ",
    "supplierCostUSD": 0.36,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check"
  },
  {
    "id": 14,
    "name": "LED Wardrobe Light",
    "category": "Home",
    "price": 14.99,
    "image": "https://www.tecnomat.it/pub/media/catalog/product/c/b/2/f/reglette_per_armadio_con_sensore_di_movimento_w_lumen_k_mm_25035187_picture_01.jpg",
    "emoji": "💡",
    "description": "Compact LED light for wardrobes, cupboards and dark storage areas.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/led-sensor-light-body-infrared-sensor-light-led-cabinet-light-p-F91CA00A-6403-435D-8E5A-5555B4D78FFA.html",
    "supplierSku": "CJJZSNSN00255-Recharge 10LED-1pcs",
    "supplierCostUSDFrom": 2.69,
    "supplierMatchStatus": "matched-awaiting-exact-variant-cost-and-uk-shipping"
  },
  {
    "id": 15,
    "name": "Digital Alarm Clock",
    "category": "Home",
    "price": 19.99,
    "image": "https://cdn0.woolworths.media/content/wowproductimages/large/1115191827_8.jpg",
    "emoji": "⏰",
    "description": "Simple digital bedside clock with an easy-read display.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/cross-border-hit-digital-bedroom-student-led-electronic-simple-mini-car-plug-in-clock-small-alarm-clock-p-1954842383395475457.html",
    "supplierSku": "CJJT245323701AZ",
    "supplierCostUSD": 4.53,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check"
  },
  {
    "id": 16,
    "name": "Adjustable Laptop Stand",
    "category": "Tech",
    "price": 24.99,
    "image": "https://www.nillkin.com/cdn/shop/products/ProDeskAdjustableLaptopStand-Sliver.jpg?v=1690029878&width=1000",
    "emoji": "💻",
    "description": "Portable adjustable stand for laptops and tablets.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/new-laptop-stand-multifunctional-folding-lift-portable-laptop-stand-monitor-increase-rack-aluminum-alloy-base-p-DCB495CC-80F8-4ED9-B5BD-26E39B751776.html",
    "supplierSku": "CJJSBGBG00898-Black-280x280x25.5mm",
    "supplierCostUSD": 11.82,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check"
  },
  {
    "id": 17,
    "name": "Mini Desktop Humidifier",
    "category": "Home",
    "price": 18.99,
    "image": "https://media.adeo.com/mkp/6d2241b63da7bde0e56a77f2a0018501/media.jpg?fit=bounds&format=jpg&height=650&quality=80&width=650",
    "emoji": "💧",
    "description": "Compact desktop humidifier for bedrooms, desks and small spaces.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/usb-mini-humidifier-large-fog-volume-small-air-hydrating-humidifier-p-1495774597293936640.html",
    "supplierSku": "CJJT142131101AZ",
    "supplierCostUSD": 2.45,
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check"
  },
  {
    "id": 18,
    "name": "Reusable Cable Ties",
    "category": "Tech",
    "price": 6.99,
    "image": "https://i5.walmartimages.com/asr/8df36d1a-fe31-4394-a5f4-d07b7149546f.2f634778be2c797cf25738f5aa01af3f.jpeg?odnBg=FFFFFF&odnHeight=2000&odnWidth=2000",
    "emoji": "🧷",
    "description": "Reusable ties for organising charging cables and desk wires.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "needs-sourcing-match",
    "sourcingNote": "No clean CJ listing found for reusable hook-and-loop cable ties."
  },
  {
    "id": 19,
    "name": "Silicone Air Fryer Liner",
    "category": "Kitchen",
    "price": 11.99,
    "image": "https://img.joomcdn.net/6c89682b8c8e9b6bc4089013d73b8dcafa48a008_original.jpeg",
    "emoji": "🍟",
    "description": "Reusable silicone liner designed to make air fryer cleanup easier.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/air-fryer-silicone-pot-replacement-of-parchment-paper-liners-no-more-cleaning-basket-after-using-the-air-fryer-food-safe-air-fryers-oven-accessories-p-1435061247828692992.html",
    "supplierSku": "CJJT127784001AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      3.93,
      5.43
    ]
  },
  {
    "id": 20,
    "name": "Kitchen Oil Spray Bottle",
    "category": "Kitchen",
    "price": 12.99,
    "image": "https://image.cdn.shpy.in/371084/SKU-8108_0-1755611834756.jpg?format=webp&width=600",
    "emoji": "🫙",
    "description": "Refillable fine-mist oil bottle for cooking and salads.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/2-in-1-oil-sprayer-bottle-bbq-cooking-oil-dispenser-olive-oil-pourers-sprayer-kitchen-baking-oil-mister-vinegar-bottle-p-1715574082122551296.html",
    "supplierSku": "CJYD187611401AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      3.01,
      5.66
    ]
  },
  {
    "id": 21,
    "name": "Magnetic Spice Jars",
    "category": "Kitchen",
    "price": 17.99,
    "image": "https://images-cdn.ubuy.co.in/65281e3112071603d93f7f41-homgen-12pcs-stainless-steel-magnetic.jpg",
    "emoji": "🧂",
    "description": "Space-saving spice containers with magnetic backing.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "needs-sourcing-match",
    "sourcingNote": "CJ has magnetic seasoning racks and spice jars, but no clean match for the current Magnetic Spice Jars listing."
  },
  {
    "id": 22,
    "name": "Silicone Sink Strainer",
    "category": "Kitchen",
    "price": 8.99,
    "image": "https://i5.walmartimages.com/asr/6d2592c9-8a1e-45a9-9004-146a35a2eba0.fc4f126d074eb5f7cf53b79d044bf6af.jpeg?odnBg=FFFFFF&odnHeight=768&odnWidth=768",
    "emoji": "🚰",
    "description": "Flexible sink strainer for catching food scraps and debris.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/sink-drain-strainer-hair-catchers-rubber-shower-bathtub-floor-filter-water-stopper-silicone-bathroom-kitchen-deodorant-plug-p-1382324639715430400.html",
    "supplierSku": "CJYS108057501AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      0.52,
      2.72
    ]
  },
  {
    "id": 23,
    "name": "Reusable Food Storage Bags",
    "category": "Kitchen",
    "price": 13.99,
    "image": "https://tm-prd-cdn.themarket.co.nz/resizer/view?b=productimages&h=1080&key=740783a859ab1e263eac67d7c6fb8ca6&w=1080",
    "emoji": "🥪",
    "description": "Reusable storage bags for snacks, lunches and food prep.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/silicone-fresh-keeping-bag-vacuum-sealed-bag-food--storage-bag-refrigerator-food-fruit-storage-bag-p-3F459E7B-ECA7-4DE5-86BB-B76413905F0C.html",
    "supplierSku": "CJJJJTCF00348-Blue-500ml",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      1.3,
      8.35
    ]
  },
  {
    "id": 24,
    "name": "Handheld Milk Frother",
    "category": "Kitchen",
    "price": 10.99,
    "image": "https://www.bigw.com.au/medias/sys_master/images/images/h69/hca/120105267691550.jpg",
    "emoji": "☕",
    "description": "Compact handheld frother for coffee, hot chocolate and shakes.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/modern-minimalist-handheld-electric-milk-powder-stirrer-p-2408020406281627600.html",
    "supplierSku": "CJYD209951701AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 1.24
  },
  {
    "id": 25,
    "name": "Manual Vegetable Chopper",
    "category": "Kitchen",
    "price": 18.99,
    "image": "https://i5.walmartimages.com/asr/24f7bd1c-2686-4db8-b38b-e27ac6ef7327.9540be5c952c8a8601cfed3cbc5ab769.jpeg?odnBg=FFFFFF&odnHeight=580&odnWidth=580",
    "emoji": "🥕",
    "description": "Compact kitchen chopper for quick everyday food preparation.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/kitchen-hand-operated-multi-functional-vegetable-cutter-rust-resistant-practical-manual-vegetable-slicer-for-home-p-1630393947791044608.html",
    "supplierSku": "CJJT169443501AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 6.09
  },
  {
    "id": 26,
    "name": "Easy Release Ice Cube Tray",
    "category": "Kitchen",
    "price": 9.99,
    "image": "https://st.bigc-cs.com/cdn-cgi/image/format%3Dwebp%2Cquality%3D90/public/media/catalog/product/50/20/2000006206350/2000006206350_3-20240528152152-.jpg",
    "emoji": "🧊",
    "description": "Flexible ice tray designed for quick, easy cube release.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/pp-material-ice-mould-quick-demould-ice-cube-tray-creative-party-bar-kitchen-freezer-cooling-drink-ice-box-silicone-molds-kitchen-gadgets-p-1798951781255487488.html",
    "supplierSku": "CJYD205527401AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      0.5,
      1.65
    ]
  },
  {
    "id": 27,
    "name": "Microwave Splatter Cover",
    "category": "Kitchen",
    "price": 12.99,
    "image": "https://image-cdn.ubuy.com/ram-pro-microwave-cover-for-food/400_400_100/697a66d7bca0ac0b940f1646.jpg",
    "emoji": "🍲",
    "description": "Ventilated food cover to help keep microwaves cleaner.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierSku": "CJYD2589002",
    "supplierMatchStatus": "candidate-needs-exact-variant-sku",
    "sourcingNote": "CJ identifies a multifunctional microwave splatter cover under this product code, but the public page did not expose a checkout-safe variant SKU."
  },
  {
    "id": 28,
    "name": "Clip-On Pot Strainer",
    "category": "Kitchen",
    "price": 10.99,
    "image": "https://image.made-in-china.com/318f0j00cERGtTuyFVrk/HK-2066-mp4.webp",
    "emoji": "🍝",
    "description": "Compact clip-on strainer for pasta, vegetables and cooked foods.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "needs-sourcing-match",
    "sourcingNote": "No clean CJ listing found for the current clip-on pot strainer style."
  },
  {
    "id": 29,
    "name": "Sofa Armrest Organiser",
    "category": "Home",
    "price": 16.99,
    "image": "https://cdn.manomano.com/sofa-organizer-armrest-holder-couch-tray-storage-bag-hanging-storage-armrest-pockets-sofa-organizer-armchair-caddy-for-books-magazine-glasses-tv-remote-control-ipad-dvd-P-41674973-161002332_1.jpg",
    "emoji": "🛋️",
    "description": "Multi-pocket organiser for remotes, phones, magazines and accessories.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "needs-sourcing-match",
    "sourcingNote": "CJ trend results show couch-arm trays, but not a clean match for the current soft sofa armrest organiser."
  },
  {
    "id": 30,
    "name": "Under-Bed Storage Organiser",
    "category": "Home",
    "price": 19.99,
    "image": "https://img.vevorstatic.com/us/CDCWFBWFBWL309XD1001V0/original_img-v1/under-bed-storage-m100-10.jpg?format=webp&timestamp=1751100891000",
    "emoji": "📦",
    "description": "Low-profile storage organiser for bedding, clothes and seasonal items.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/foldable-clothes-storage-bag-large-capacity-organizer-with-handle-and-double-zipper-for-bedding-moving-travel-under-bed-storage-p-2505160457141629100.html",
    "supplierSku": "CJYD237778201AZ",
    "supplierMatchStatus": "candidate-duplicate-review",
    "supplierCostUSDRange": [
      0.98,
      5.65
    ],
    "sourcingNote": "Good product match, but this is the same CJ family already used by product 7. Decide whether to keep both listings."
  },
  {
    "id": 31,
    "name": "Adjustable Drawer Divider Set",
    "category": "Home",
    "price": 15.99,
    "image": "https://cdn.shopify.com/s/files/1/0761/5771/4658/files/61g3wVQvECL._AC_SX679_PIbundle-5_TopRight_0_0_SH20.jpg?v=1756561222",
    "emoji": "🗄️",
    "description": "Expandable dividers for keeping drawers neat and organised.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "needs-sourcing-match",
    "sourcingNote": "CJ confirms adjustable drawer dividers as a product type, but no checkout-safe variant SKU was found."
  },
  {
    "id": 32,
    "name": "Bathroom Shower Caddy",
    "category": "Home",
    "price": 17.99,
    "image": "https://www.thursdayliving.com.au/cdn/shop/files/100725-3_07f2c409-a683-4abc-9c1b-a891e6e8be72.jpg?v=1754364230&width=1000",
    "emoji": "🚿",
    "description": "Compact shower organiser for toiletries and bathroom essentials.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/1pc-wall-mounted-bathroom-shelf-shower-caddy-rack-no-punching-triangle-storage-rack-for-bathroom-kitchen-bathroom-accessories-p-1880165726661005314.html",
    "supplierSku": "CJYS227337901AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 5.8,
    "sourcingNote": "CJ page also shows an $8.80 free-shipping price; live UK checkout must decide the real landed cost."
  },
  {
    "id": 33,
    "name": "Travel Shoe Storage Bags",
    "category": "Travel",
    "price": 12.99,
    "image": "https://ribbi.nl/cdn/shop/files/1200x818_b169770c-a79b-40e6-8a0f-0818f840a464_800x.jpg?v=1720930831",
    "emoji": "👟",
    "description": "Lightweight travel bags for keeping shoes separate inside luggage.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "needs-sourcing-match",
    "sourcingNote": "No clean standalone travel shoe-storage-bag match found without duplicating the packing-cube set."
  },
  {
    "id": 34,
    "name": "Bedside Pocket Organiser",
    "category": "Home",
    "price": 13.99,
    "image": "https://dreamsleepaustralia.com.au/cdn/shop/files/2_9bd47ec8-9693-4714-a674-6bbfbb436d37_1000x.png?v=1746125237",
    "emoji": "🛏️",
    "description": "Hanging bedside organiser for books, remotes, phones and accessories.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/non-woven-storage-hanging-bag-multi-layer-hanging-type-p-1377611667902435328.html",
    "supplierSku": "CJGJ106277501AZ",
    "supplierMatchStatus": "candidate-title-use-review",
    "supplierCostUSD": 2.79,
    "sourcingNote": "Hanging storage bag is close to a bedside pocket organiser, but the supplier describes it as a wall/door hanging organiser."
  },
  {
    "id": 35,
    "name": "Microfibre Cleaning Slippers",
    "category": "Home",
    "price": 9.99,
    "image": "https://image.made-in-china.com/2f0j00iMBVUDkogTGZ/Houseware-Cleaning-Microfiber-Chenille-Dusting-Slippers.webp",
    "emoji": "🥿",
    "description": "Soft microfibre slippers designed for light floor dusting while walking.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "needs-sourcing-match",
    "sourcingNote": "CJ trend content confirms microfiber cleaning slippers, but no checkout-safe product SKU was found."
  },
  {
    "id": 36,
    "name": "Portable Pet Water Bottle",
    "category": "Pets",
    "price": 15.99,
    "image": "https://f.fcdn.app/imgs/a0a352/www.atrixuy.com/atriuy/de3f/original/catalogo/TBANI300_BLANCO_1/600x600/bebedero-portatil-mascotas-boton-dispensador-agua-viaje-color-variante-blanco.jpg",
    "emoji": "🐕",
    "description": "Portable water bottle for dogs during walks and travel.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/2-in-1-portable-dog-water-bottle-for-small-big-dogs-cat-outdoor-leak-proof-puppy-drinking-bowl-with-food-container-pets-feeder-pet-products-p-2504100230321610200.html",
    "supplierSku": "CJYD235019202BY",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      2.21,
      2.77
    ]
  },
  {
    "id": 37,
    "name": "Slow Feeder Dog Bowl",
    "category": "Pets",
    "price": 14.99,
    "image": "https://tassukauppa.fi/WebRoot/elisa03/Shops/tassukauppa/63F6/711B/93E2/101E/A583/0A28/1012/16D3/Duvo_Slow_Feeder_ahmimisenestokuppi_koiralle_petrooli_S_LG14292.jpg",
    "emoji": "🥣",
    "description": "Patterned feeding bowl designed to encourage slower eating.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/pet-dog-cat-slow-feeder-bowls-anti-choking-slow-feeder-dish-bowl-home-dog-eating-plate-anti-gulping-bowl-supplies-p-1653041912300969984.html",
    "supplierSku": "CJGY174846501AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      1.29,
      2.11
    ]
  },
  {
    "id": 38,
    "name": "Self-Cleaning Cat Grooming Brush",
    "category": "Pets",
    "price": 13.99,
    "image": "https://cdn.shopify.com/s/files/1/0573/2463/4249/files/self_cleaning_sliker_brush_detail.png?v=1693189057",
    "emoji": "🐈",
    "description": "Grooming brush with an easy-release design for loose pet hair.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/pet-needle-comb-hair-remover-brush-dog-and-cat-pet-comb-self-cleaning-massage-brushes-grooming-supplies-p-2407110256221627600.html",
    "supplierSku": "CJYD208071305EV",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 1.19
  },
  {
    "id": 39,
    "name": "Adjustable Pet Seat Belt",
    "category": "Pets",
    "price": 9.99,
    "image": "https://assets.petco.com/petco/image/upload/c_pad%2Cdpr_1.0%2Cf_auto%2Cq_auto%2Ch_636%2Cw_636/c_pad%2Ch_636%2Cw_636/3350102-center-1",
    "emoji": "🚗",
    "description": "Adjustable restraint strap for safer car journeys with pets.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/adjustable-pet-cat-dog-car-seat-belt-pet-seat-vehicle-dog-harness-lead-clip-safety-lever-traction-dog-collars-dogs-accessoires-pets-products-p-1383313727658528768.html",
    "supplierSku": "CJQC108431101AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      0.52,
      0.54
    ]
  },
  {
    "id": 40,
    "name": "Dog Paw Cleaner Cup",
    "category": "Pets",
    "price": 12.99,
    "image": "https://www.vour.gr/product_application/catalogmanager/assets/images/20220628143618_0.jpg",
    "emoji": "🐾",
    "description": "Portable paw cleaner with soft flexible cleaning bristles.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "needs-sourcing-match",
    "sourcingNote": "CJ confirms the paw-cleaner-cup product type, but no checkout-safe CJ variant SKU was found."
  },
  {
    "id": 41,
    "name": "Pet Treat Training Pouch",
    "category": "Pets",
    "price": 14.99,
    "image": "https://www.tiendanimal.es/dw/image/v2/BDLQ_PRD/on/demandware.static/-/Sites-kiwoko-master-catalog/default/dwa326554b/images/large/f17ddac57b0e4d0d8e2f5a954788ee76.jpg?q=85&sh=780&sm=fit&sw=780",
    "emoji": "🦴",
    "description": "Hands-free pouch for treats, waste bags and small training accessories.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/dog-training-leash-waist-bag-hands-free-outdoor-pet-running-walking-leash-portable-dog-food-water-cup-storage-bags-p-1392067844971302912.html",
    "supplierSku": "CJGY112387101AZ",
    "supplierMatchStatus": "candidate-variant-review",
    "supplierCostUSDRange": [
      3.32,
      16.75
    ],
    "sourcingNote": "The product family includes the treat/storage pouch function, but variant selection changes what the customer receives."
  },
  {
    "id": 42,
    "name": "Travel Makeup Organiser",
    "category": "Accessories",
    "price": 18.99,
    "image": "https://igadgitz.com/cdn/shop/files/b7bb33e7-b339-475d-9bfd-1a75390ff00f_1800x1800.jpg?v=1738923558",
    "emoji": "💄",
    "description": "Multi-compartment makeup bag for holidays and everyday storage.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/travel-cosmetic-bag-large-capacity-multifunction-travel-cosmetic-bag-women-toiletries-organizer-female-storage-make-up-case-tool-p-1546430072087916544.html",
    "supplierSku": "CJNS152304201AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      1.46,
      1.58
    ]
  },
  {
    "id": 43,
    "name": "Heatless Curling Set",
    "category": "Beauty",
    "price": 11.99,
    "image": "https://silvercloudbeauty.com/cdn/shop/files/Caramel_Heatess_Curlers_1.jpg?v=1762172441&width=1200",
    "emoji": "🎀",
    "description": "Soft overnight styling set for heat-free curls and waves.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "needs-sourcing-match",
    "sourcingNote": "CJ confirms heatless curling sets as a current product type, but no direct checkout-safe CJ variant SKU was found."
  },
  {
    "id": 44,
    "name": "Makeup Brush Cleaning Pad",
    "category": "Beauty",
    "price": 7.99,
    "image": "https://i5.walmartimages.com/asr/dfd91dcc-0d94-4b20-aa2f-d4b46afa13c8.a82d36d0679bdd7b2db95f8606a4f439.jpeg",
    "emoji": "🖌️",
    "description": "Textured silicone pad for cleaning makeup brushes and cosmetic tools.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "needs-sourcing-match",
    "sourcingNote": "CJ confirms silicone makeup-brush cleaning mats as a current product type, but no direct product SKU was found."
  },
  {
    "id": 45,
    "name": "Satin Sleep Mask",
    "category": "Beauty",
    "price": 9.99,
    "image": "https://satinluxuryline.com/cdn/shop/files/16ASleepmask_recht_van_voren_roze_528d7372-6c08-483f-8d58-5f9b5076919b.jpg?v=1716319412&width=535",
    "emoji": "😴",
    "description": "Soft sleep mask for travel, naps and bedtime routines.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/eye-patch-imitated-silk-eye-patch-shading-sleeping-eye-mask-travel-relax-covers-eye-shade-health-sleeping-shield-eye-care-tools-p-1692297554018447360.html",
    "supplierSku": "CJYD182485601AZ",
    "supplierMatchStatus": "candidate-material-title-review",
    "supplierCostUSD": 0.68,
    "sourcingNote": "CJ describes this as imitation silk/rayon. Rename the store item to Silky Sleep Mask unless a true satin variant is sourced."
  },
  {
    "id": 46,
    "name": "Jewellery Cleaning Pen",
    "category": "Accessories",
    "price": 8.99,
    "image": "https://www.valeriemadison.com/cdn/shop/files/WBcleaningpen.jpg?v=1720635615",
    "emoji": "✨",
    "description": "Compact cleaning pen for quick jewellery touch-ups.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "needs-sourcing-match",
    "sourcingNote": "No clean CJ match found for a jewellery-cleaning pen."
  },
  {
    "id": 47,
    "name": "Silicone Scalp Massager",
    "category": "Beauty",
    "price": 8.99,
    "image": "https://5thave-img-cdn.beyondstyle.us/pf/bdacec14-10df-3aa2-955e-4bbebf6416b7.jpg?x-oss-process=style%2Fs1",
    "emoji": "💆",
    "description": "Soft silicone scalp brush for shampooing and massage.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/silicone-shampoo-head-brush-p-EC1FAEF4-5F97-462F-A67C-CDECF93BC026.html",
    "supplierSku": "CJJJJTJT51194-Pink",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      0.26,
      8.15
    ]
  },
  {
    "id": 48,
    "name": "Resistance Band Set",
    "category": "Fitness",
    "price": 17.99,
    "image": "https://images.fyndiq.se/images/f_auto/t_600x600/prod/fdf2e18e548941b2/30bd544ac87b/5-pack-traningsband-gummiband-motstandsband-traningsband-multicolor-multifarg-0bc8718cbb254c57",
    "emoji": "🏋️",
    "description": "Portable resistance bands for home workouts and stretching.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/resistance-loop-exercise-bands-resistance-bands-exercise-bands-for-home-fitness-stretching-strength-training-physical-therapyelastic-workout-bands-for-women-men-kids-set-of-5-p-1809772680481492992.html",
    "supplierSku": "CJJM207746801AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 10.98
  },
  {
    "id": 49,
    "name": "Yoga Stretch Strap",
    "category": "Fitness",
    "price": 9.99,
    "image": "https://arrowmax.in/cdn/shop/files/4_9da76538-9cfe-4d8e-ad36-bd57cc14dd5f.jpg?v=1758272516",
    "emoji": "🧘",
    "description": "Simple stretching strap for yoga, mobility and flexibility work.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/rehabilitation-lajin-band-yoga-stretch-band-auxiliary-ligament-p-1441219130710691840.html",
    "supplierSku": "CJJT129735301AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 1.48
  },
  {
    "id": 50,
    "name": "Adjustable Hand Grip Trainer",
    "category": "Fitness",
    "price": 12.99,
    "image": "https://m.media-amazon.com/images/I/61kzUOq0L5L._AC_SL1500_.jpg",
    "emoji": "💪",
    "description": "Compact hand and forearm grip trainer with adjustable resistance.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/hand-grip-strengthener-grip-strength-trainer-and-finger-exerciser-silicone-adjustable-hand-grip-20-80lb-gripping-ring-finger-forearm-trainer-carpal-expander-muscle-workout-exercise-p-1659909774420889600.html",
    "supplierSku": "CJJM1761950-Atrovirens",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      6.6,
      18.6
    ],
    "sourcingNote": "Choose the exact resistance/colour variant before launch because CJ pricing varies widely."
  },
  {
    "id": 51,
    "name": "Running Waist Belt",
    "category": "Fitness",
    "price": 14.99,
    "image": "https://fitletic.com/cdn/shop/products/0003_Blitz-Sports-and-Travel-Belt-Reflective-Black_600x.webp?v=1690219277",
    "emoji": "🏃",
    "description": "Slim waist belt for carrying phones, keys and cards while running.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/ultra-thin-running-waterproof-portable-close-fitting-reflective-sports-phone-waist-bag-p-2407010655361627900.html",
    "supplierSku": "CJYD207289401AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 2.11
  },
  {
    "id": 52,
    "name": "Travel Packing Cube Set",
    "category": "Travel",
    "price": 19.99,
    "image": "https://upandgr8.com/cdn/shop/files/9_b2d47f24-0e7c-4fd3-80d8-19040ccbba85.jpg?v=1715168268",
    "emoji": "🧳",
    "description": "Lightweight packing organisers for keeping luggage tidy.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/8-piece-set-luggage-divider-bag-travel-storage-clothes-underwear-shoes-organizer-packing-cube-bag-p-1386852733046362112.html",
    "supplierSku": "CJNS110086901AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      2.27,
      4.62
    ]
  },
  {
    "id": 53,
    "name": "Luggage Cup Holder",
    "category": "Travel",
    "price": 12.99,
    "image": "https://www.riemot.com/cdn/shop/products/1_93a0022e-3eac-49c5-b5f2-32ad15613dbf_1080x.jpg?v=1638172601",
    "emoji": "🥤",
    "description": "Strap-on luggage organiser for drinks, phones and small travel items.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "needs-sourcing-match",
    "sourcingNote": "CJ has luggage with built-in cup holders and generic cup holders, but no clean match for the strap-on luggage cup holder listing."
  },
  {
    "id": 54,
    "name": "RFID Passport Wallet",
    "category": "Travel",
    "price": 14.99,
    "image": "https://sc3.locondo.jp/contents/commodity_image/RE/RE4112DW06149_1_l.jpg",
    "emoji": "🛂",
    "description": "Compact travel wallet for passports, cards and documents.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/rfid-antimagnetic-passport-holder-leather-id-case-p-1BA30466-381C-44A5-8A86-8A2DFDF29A4C.html",
    "supplierSku": "CJBHNSNS10068-Black",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 3.35
  },
  {
    "id": 55,
    "name": "Car Seat Gap Organiser",
    "category": "Car",
    "price": 17.99,
    "image": "https://trunkistore.com/cdn/shop/files/20260105_2039_CarSeatGapFiller_remix_01ke6vsd59e74aymz7xhcd5bhj.png?v=1767609816&width=1024",
    "emoji": "🚙",
    "description": "Slim organiser for phones, keys and small items beside the car seat.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://www.cjdropshipping.com/product/car-seat-gap-filler-organizer-car-seat-console-organizer-for-keys-phones-and-sunglasses-p-1803978693954916352.html",
    "supplierSku": "CJQC206507501AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSDRange": [
      4.34,
      8.46
    ]
  },
  {
    "id": 56,
    "name": "Car Interior Cleaning Gel",
    "category": "Car",
    "price": 8.99,
    "image": "https://p16-oec-general-useast5.ttcdn-us.com/tos-useast5-i-omjb5zjo8w-tx/860f17d68f0744289891ffcd3338ff85~tplv-fhlh96nyum-crop-webp%3A1500%3A1500.webp?dr=12190&from=2378011839&idc=useast5&ps=933b5bde&shcp=e1be8f53&shp=8dbd94bf&t=555f072d",
    "emoji": "🧽",
    "description": "Reusable cleaning gel for vents, cup holders and awkward interior gaps.",
    "fulfillmentReady": false,
    "supplierMatchStatus": "needs-sourcing-match",
    "sourcingNote": "CJ confirms car/keyboard cleaning gel as a product type, but no exact checkout-safe gel SKU was found."
  },
  {
    "id": 57,
    "name": "Mini Car Rubbish Bin",
    "category": "Car",
    "price": 13.99,
    "image": "https://zybux.co.uk/cdn/shop/files/7_7398c628-7f62-403b-952b-9cc323d7b562_1445x.png?v=1684848608",
    "emoji": "🗑️",
    "description": "Compact car bin for wrappers, tissues and everyday rubbish.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/car-door-container-trash-can-p-2505210708001621800.html",
    "supplierSku": "CJYD238181101AZ",
    "supplierMatchStatus": "matched-awaiting-uk-shipping-check",
    "supplierCostUSD": 2.28
  },
  {
    "id": 58,
    "name": "Hard Shell Sunglasses Case",
    "category": "Accessories",
    "price": 10.99,
    "image": "https://knockaround.com/cdn/shop/products/KA_Hard_Shell_Black_Front.jpg?v=1761056420&width=1024",
    "emoji": "🕶️",
    "description": "Protective glasses case with a compact hard-shell design.",
    "fulfillmentReady": false,
    "supplier": "CJdropshipping",
    "supplierUrl": "https://cjdropshipping.com/product/litchi-sunglasses-case-p-D2520D4F-0058-4148-AF2B-DF7E157539F3.html",
    "supplierSku": "CJNSFSYJ00303-Black a",
    "supplierMatchStatus": "candidate-material-title-review",
    "supplierCostUSDRange": [
      0.54,
      6.2
    ],
    "sourcingNote": "This is a protective leather sunglasses case, not explicitly a hard-shell case. Rename or source a confirmed hard-shell model."
  }
];

// fulfillmentReady remains false until exact variant, live UK shipping and supplier validation pass.
